version: '3'
services:
  db:
    image: postgres
    container_name: cryptchat-db
    volumes:
      - /shared/postgresql/data:/var/lib/postgresql/data
    env_file:
      - variables.env
    expose:
      - '5432'
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init.sh
  web:
    build: .
    container_name: cryptchat-web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    env_file:
      - variables.env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://db:5432
    depends_on:
      - db
