development:
  :account_sid: <%= ENV.fetch('CRYPTCHAT_TWILIO_ACCOUNT_SID') { 'AC61e2c567d230b0c0c60345622e583008' } %>
  :auth_token: <%= ENV.fetch('CRYPTCHAT_TWILIO_AUTH_TOKEN') { '54c4b5cbf34acbf7a9c5e7347cb07d45' } %>
  :from: <%= ENV.fetch('CRYPTCHAT_TWILIO_FROM') { '+966501234567' } %>

production:
  :account_sid: <%= ENV.fetch('CRYPTCHAT_TWILIO_ACCOUNT_SID') %>
  :auth_token: <%= ENV.fetch('CRYPTCHAT_TWILIO_AUTH_TOKEN') %>
  :from: <%= ENV.fetch('CRYPTCHAT_TWILIO_FROM') %>

test:
  :account_sid: 'AC61e2c567d230b0c0c60345622e583008'
  :auth_token: '54c4b5cbf34acbf7a9c5e7347cb07d45'
  :from: '+966501234567'
